Astaguru/Models/AdminCms/Faq.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Faq
    {
        public string Sr { get; set; }
        public int Id { get; set; }

        [Required(ErrorMessage = "Category is Required ")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Title is Required ")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is Required ")]
        public string Description { get; set; }

       public List<Faq> GridList { get; set; }
    }
}

Astaguru/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Astaguru.Models
{
    public class Blog
    {
        public int BlogId { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Image is required.")]
        public string Image { get; set; }

        [Required(ErrorMessage = "Post date is required.")]
        public string PostDate { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        public string Description { get; set; }

        public string Sr { get; set; }

        public List<Blog> Gridlist { get; set; }

        public string imgPreview { get; set; }

        [Required(ErrorMessage = "CreatedBy is required.")]
        public string CreatedBy { get; set; }

        public string Slug { get; set; }
        public int categoryid { get; set; }

        //[Required(ErrorMessage = "Please Select Category")]
        public string category { get; set; }

        public IEnumerable<SelectListItem> CategoryList { get; set; }

    }
}

Astaguru/Models/Careers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models
{
    public class Careers
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter First Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter Email Address")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Enter Valid Email Address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Job Title")]
        public string JobTitle { get; set; }

        [Required(ErrorMessage = "Enter Messages")]
        public string Message { get; set; }

        [Required(ErrorMessage = "Enter Hear About Us")]
        public string aboutus { get; set; }

        [Required(ErrorMessage = "Please Upload Resume")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.doc|.docx|.pdf)$", ErrorMessage = "Only Document files allowed.")]
        public string Resume { get; set; }

        //public string ApplyDate { get; set; }

        //public string Sr { get; set; }

        public List<Careers> ApplyForJobList { get; set; }
    }
}

Astaguru/Models/ContactUsForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models
{
    public class ContactUsForm
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Enter Valid Email Address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone required.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Queries required.")]
        public string Queries { get; set; }
    }
}

Astaguru/Models/Video.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Astaguru.Models
{
    public class Video
    {
        public string Sr { get; set; }
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Title")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please Enter VideoUrl")]
        public string VideoUrl { get; set; }

        [Required(ErrorMessage = "Post date is required.")]
        public string PostDate { get; set; }

        public int categoryid { get; set; }

        //[Required(ErrorMessage = "Please Select Category")]
        public string category { get; set; }

        public IEnumerable<SelectListItem> CategoryList { get; set; }

        public List<Video> GridList { get; set; }
    }
}

Astaguru/Controllers/MobileAppController.cs
using Astaguru.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Astaguru.Controllers
{
    public class MobileAppController : Controller
    {
        Utility util = new Utility();

        // GET: MobileApp
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult AboutUs()
        {
            var data = CMS(1);
            TempData["desc"] = data;
            return View();
        }

        public ActionResult Services()
        {

            int pageid = 1;
            ViewBag.Services = GetPageCMSMaster(pageid);
            return View();
        }

        public ActionResult valuation()
        {

            ViewBag.Valuation = CMS(3);
            return View();
        }


        public ActionResult howtobuy()
        {
            int Pageid = 3;
            ViewBag.howtobuy = GetPageCMSMaster(Pageid);
            return View();
        }

        public ActionResult howToSell()
        {
            int Pageid = 4;
            ViewBag.howToSell = GetPageCMSMaster(Pageid);
            return View();
        }

        public ActionResult contactUs()
        {

            return View();
        }


        public ActionResult Careers()
        {

            ViewBag.CareerDesc = CMS(2);
            ViewBag.CurrentVacancy = CurrentVacancy();
            return View();
        }



        public string CurrentVacancy()
        {
            string response = "";
            StringBuilder strbuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_Current_Vacancy 'get'");
            int Count = 1;
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {
                    if (Count == 1)
                    {
                        strbuild.Append("<div class='card'>");
                        strbuild.Append("<div class='card-header' id='headingOne'>");
                        strbuild.Append("<h5 class='mb-0'>");
                        strbuild.Append("<button class='btn btn-link' type='button' data-toggle='collapse' data-target='#" + Generateslg(dr["Job_Title"].ToString()) + "' aria-expanded='true' aria-controls='collapseOne'>");
                        strbuild.Append(dr["Job_Title"].ToString());
                        strbuild.Append("</button>");
                        strbuild.Append("</h5>");
                        strbuild.Append("</div>");
                        strbuild.Append("<div id=" + Generateslg(dr["Job_Title"].ToString()) + " class='collapse show' aria-labelledby='headingOne' data-parent='#accordionExample'>");
                        strbuild.Append("<div class='card-body'>");
                        strbuild.Append("<h5 class='sbold black'>Job Title:</h5>");
                        strbuild.Append("<p>" + dr["Job_Title"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Business Unit:</h5>");
                        strbuild.Append("<p>" + dr["Business_Unit"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Job Responsibility:</h5>");
                        strbuild.Append("<p>" + dr["Job_Responsibility"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Responsibilities:</h5>");
                        strbuild.Append(dr["Responsibilities"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Functional Skills:</h5>");
                        strbuild.Append(dr["Functional_Skills"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Technical Skills:</h5>");
                        strbuild.Append(dr["Technical_skills"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Required Qualification:</h5>");
                        strbuild.Append("<p>" + dr["Qualification"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Salary:</h5>");
                        strbuild.Append("<p>" + dr["Salary"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Experience:</h5>");
                        strbuild.Append("<p>" + dr["Experience"].ToString() + "</p>");
                        strbuild.Append("<a href='#apply_now_form' class='a_scroll btn_grey_dark mobile_only extra-margin-top-20'><span>Apply Now</span></a>");
                        strbuild.Append("</div>");
                        strbuild.Append("</div>");
                        strbuild.Append("</div>");
                    }
                    else
                    {
                        strbuild.Append("<div class='card'>");
                        strbuild.Append("<div class='card-header' id='headingTwo'>");
                        strbuild.Append("<h5 class='mb-0'>");
                        strbuild.Append("<button class='btn btn-link collapsed' type='button' data-toggle='collapse' data-target='#" + Generateslg(dr["Job_Title"].ToString()) + "' aria-expanded='false' aria-controls='collapseTwo'>");
                        strbuild.Append(dr["Job_Title"].ToString());
                        strbuild.Append("</button>");
                        strbuild.Append("</h5>");
                        strbuild.Append("</div>");
                        strbuild.Append("<div id=" + Generateslg(dr["Job_Title"].ToString()) + " class='collapse' aria-labelledby='headingTwo' data-parent='#accordionExample'>");
                        strbuild.Append("<div class='card-body'>");
                        strbuild.Append("<h5 class='sbold black'>Job Title:</h5>");
                        strbuild.Append("<p>" + dr["Job_Title"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Business Unit:</h5>");
                        strbuild.Append("<p>" + dr["Business_Unit"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Job Responsibility:</h5>");
                        strbuild.Append("<p>" + dr["Job_Responsibility"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Responsibilities:</h5>");
                        strbuild.Append(dr["Responsibilities"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Functional Skills:</h5>");
                        strbuild.Append(dr["Functional_Skills"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Technical Skills:</h5>");
                        strbuild.Append(dr["Technical_skills"].ToString());
                        strbuild.Append("<h5 class='sbold black'>Required Qualification:</h5>");
                        strbuild.Append("<p>" + dr["Qualification"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Salary:</h5>");
                        strbuild.Append("<p>" + dr["Salary"].ToString() + "</p>");
                        strbuild.Append("<h5 class='sbold black'>Experience:</h5>");
                        strbuild.Append("<p>" + dr["Experience"].ToString() + "</p>");
                        strbuild.Append("<a href='#apply_now_form' class='a_scroll btn_grey_dark mobile_only extra-margin-top-20'><span>Apply Now</span></a>");
                        strbuild.Append("</div>");
                        strbuild.Append("</div>");
                        strbuild.Append("</div>");
                    }

                    Count++;
                }

            }

            response = strbuild.ToString();
            return response;
        }


        public ActionResult privacyPolicy()
        {

            ViewBag.Policy = CMS(4);
            return View();
        }

        public ActionResult TermsAndConditions()
        {
            int pageid = 2;
            ViewBag.TermsAndConditions = GetPageCMSMaster(pageid);
            return View();
        }

        public ActionResult Departments()
        {

            return View();
        }

        public ActionResult deptEstate()
        {

            return View();
        }

        public ActionResult deptFine()
        {

            return View("");
        }

        public ActionResult deptFurniture()
        {
            return View();
        }

        public ActionResult deptIndian()
        {

            return View();
        }

        public ActionResult deptModernArt()
        {

            return View();
        }

        public ActionResult deptJewellery()
        {

            return View();
        }

        public ActionResult deptMemorabilia()
        {

            return View();
        }

        public ActionResult deptNumismatic()
        {

            return View();
        }

        public ActionResult deptBooks()
        {

            return View();
        }

        public ActionResult deptScience()
        {

            return View();
        }

        public ActionResult deptSoutheast()
        {

            return View();
        }


        public ActionResult deptTexilesView1()
        {

            return View();
        }

        public ActionResult Timepieces()
        {
            return View();
        }

        public ActionResult deptClassic()
        {

            return View();
        }


        #region video
        public ActionResult video()
        {

            Video obj = new Video();
            obj.CategoryList = BindcategoryforVideo(obj);
            return View(obj);
        }

        [HttpPost]

Astaguru/Views/MobileApp/deptFine.cshtml

@{
    Layout = null;
    string baseUrlPath = Astaguru.Services.Common.baseUrlPath;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="icon" href="~/Content/favicon.jpg" type="image/jpg" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i|Prata|Roboto+Condensed:400,700" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/slick.css">
    <link rel="stylesheet" id="theme" href="~/Content/css/selectric.css">
    <link href="~/Content/css/sumoselect.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/css/easy-responsive-tabs.css " />
    <link rel="stylesheet" href="~/Content/css/jquery.fancybox.css" />
    <link href="~/Content/css/lightslider.css" rel="stylesheet" />
    <link href="~/Content/css/photoviewer.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/style.css" />

    <script src="~/Content/js/script.js"></script>
    <script src="~/Content/js/jquery-2.1.1.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/slick.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.selectric.js"></script>
    <script src="~/Content/js/jquery.sumoselect.js" type="text/javascript"></script>
    <script src="~/Content/js/easyResponsiveTabs.js"></script>

    <script src="~/Content/js/cloudzoom.js"></script>
    <script src="~/Content/js/thumbelina.js"></script>
    <script src="~/Content/js/jquery.fancybox.js"></script>
    <script src="~/Content/js/lightslider.js"></script>
    <script src="~/Content/js/photoviewer.js"></script>
    <script src="~/Content/js/readmore.js"></script>

    <script src="~/Content/js/commonJs.js"></script>
    <script src="~/Content/js/modernizr.js"></script>

    <script src="~/Content/js/jquery.time-to.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>
    @*<div id="wrapper" class="footer_pages_content">*@
        <div class="container-fluid content extra-padding-top-40 extra-padding-bottom-100">
            <div class="title_flex">
                <h3 class="sbold uppercase">Fine Writing Instruments</h3>

                @*<a href="@baseUrlPath/MobileApp/Departments" class="link_back"><i class="icon-prev"></i> Back</a>*@
            </div>

            <div class="row custom_row">
                <div class="col-md-6 extra-margin-top-40 custom_col">
                    <p>The history of the world as we know it would have been lost through the centuries if it wasn’t for the mighty yet humble writing aides. Despite technological developments or perhaps because of it, a pen continues to hold its sovereignty. Centenarian establishments such as Mont Blanc and Montegrappa have safeguarded this legacy which has been passed down from one generation to another.</p>
                    <p>At AstaGuru we have featured remarkable masterpieces such Mont Blanc’s Year of the Golden Dragon edition pen and a sterling silver piston filling fountain pen by Montegrappa that was inspired by the design of Saint Peter’s Cathedral, at our past auctions.</p>
                    <p class="color_light">The GST on all sales under this segment is charged at 12% on full sale value in accordance ‘Goods & Service Tax’ regulations.</p>
                    
                </div><!-- col -->
                <div class="col-md-6 extra-margin-top-40 custom_col text-right">
                    <div class="video_department"><iframe width="100%" class="" src="https://www.youtube.com/embed/DqIKuNDpycM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe></div>
                </div><!-- col -->
            </div><!-- row -->

            <div class="row">
               
            </div><!-- row -->
        </div><!-- content -->

    @*</div>*@<!-- Wrapper -->
</body>
</html>

Astaguru/Views/MobileApp/howtobuy.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="icon" href="~/Content/favicon.jpg" type="image/jpg" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i|Prata|Roboto+Condensed:400,700" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/slick.css">
    <link rel="stylesheet" id="theme" href="~/Content/css/selectric.css">
    <link href="~/Content/css/sumoselect.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/css/easy-responsive-tabs.css " />
    <link rel="stylesheet" href="~/Content/css/jquery.fancybox.css" />
    <link href="~/Content/css/lightslider.css" rel="stylesheet" />
    <link href="~/Content/css/photoviewer.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/style.css" />

    <script src="~/Content/js/script.js"></script>
    <script src="~/Content/js/jquery-2.1.1.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/slick.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.selectric.js"></script>
    <script src="~/Content/js/jquery.sumoselect.js" type="text/javascript"></script>
    <script src="~/Content/js/easyResponsiveTabs.js"></script>

    <script src="~/Content/js/cloudzoom.js"></script>
    <script src="~/Content/js/thumbelina.js"></script>
    <script src="~/Content/js/jquery.fancybox.js"></script>
    <script src="~/Content/js/lightslider.js"></script>
    <script src="~/Content/js/photoviewer.js"></script>
    <script src="~/Content/js/readmore.js"></script>

    <script src="~/Content/js/commonJs.js"></script>
    <script src="~/Content/js/modernizr.js"></script>

    <script src="~/Content/js/jquery.time-to.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>
    @*<div id="wrapper" class="footer_pages_content">*@
        <div class="container-fluid content extra-padding-bottom-100 extra-padding-top-40">
            <div class="title_spbtn">
                <h3 class="sbold uppercase">How to buy</h3>
                <a href="#" class="see_video" data-toggle="modal" data-target="#SeeVideoModal" data-thevideo="https://www.youtube.com/embed/-V9WmhujSx4"><i class="icon-play"></i> Click here to see the video</a>
            </div>
            <div class="accordion extra-margin-top-40" id="accordionExample">
                @Html.Raw(ViewBag.howtobuy)
            </div>
        </div><!-- content -->

    @*</div>*@<!-- Wrapper -->
</body>
</html>

Astaguru/Views/MobileApp/video.cshtml
@model Astaguru.Models.Video
@{
    Layout = null;


    Astaguru.Services.UserService.VideoService PAS = new Astaguru.Services.UserService.VideoService();
    string baseUrlPath = Astaguru.Services.Common.baseUrlPath;


    string categoryid = Model.categoryid.ToString();


    string Subquery = string.Empty;
    if (@HttpContext.Current.Session["SubqueryPast"] != null)
    {
        Subquery = @HttpContext.Current.Session["SubqueryPast"].ToString();
    }
    int page = 0;
    double PrePage = 0;
    double NextPage = 0;
    if (string.IsNullOrEmpty(Request.QueryString["page"]))
    {

    }
    else
    {
        page = Convert.ToInt32(Request["page"].ToString());
        PrePage = Convert.ToInt32(Request["page"].ToString());
        NextPage = Convert.ToInt32(Request["page"].ToString());
    }


    double TotalPaginationCount = PAS.GetVideoCount(Subquery, categoryid);

    double pagenationOffSet = TotalPaginationCount / Convert.ToDouble(6);
    pagenationOffSet = Astaguru.Services.Common.getPaginationRoundupValue(pagenationOffSet);


    List<Astaguru.Models.Video> Videolist = null;
    Videolist = PAS.GetVideoList(Subquery, page, categoryid);


}

<!DOCTYPE html>

<html>
<head>
  
    <link rel="icon" href="~/Content/favicon.jpg" type="image/jpg" />

    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/Content/css/style.css" />

    <script src="~/Content/js/script.js"></script>
    <script src="~/Content/js/jquery-2.1.1.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>


    <script src="~/Content/js/jquery.time-to.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/aos.css" rel="stylesheet" />
    <link href="~/Content/css/astaguru_inner_pages.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="~/Content/js/aos.js"></script>


</head>
<body>
    @*<div id="wrapper" class="footer_pages_content video_equal_box_wrap">*@
        @*<div class="container-fluid content extra-padding-bottom-100 extra-padding-top-40">*@
            <div class="container pt-4" id="videos">
                @using (Html.BeginForm("video", "MobileApp", FormMethod.Post, new { id = "myform" }))
            {

                    <div class="row justify-content-between align-items-center mb-4">
                        <div class="col-6 col-lg-3">
                            <h1 class="mb-0">Videos</h1>
                        </div>
                        <div class="col-6 col-lg-3 text-right">

                            @Html.DropDownListFor(model => model.categoryid, Model.CategoryList, "Categories", new { @id = "ddlCategorylist", @class = "category" })
                            @Html.HiddenFor(m => m.categoryid, new { id = "hdncategoryid" })

                            @*<select class="category">
                                    <option selected>Categories</option>
                                    <option>Lorem Ipsum</option>
                                    <option>Lorem Ipsum</option>
                                    <option>Lorem Ipsum</option>
                                    <option>Lorem Ipsum</option>
                                    <option>Lorem Ipsum</option>
                                </select>*@
                        </div>
                    </div>
                }

                <div class="row justify-content-center">
                    @if (Videolist.Count > 0)
                    {
                        foreach (var item in Videolist)
                        {
                            <div class="col-sm-6 col-lg-4 mb-5 aos-item" data-aos="fade-up">
                                <a class="box fadeAnim">
                                    <div class="vidData">
                                        @*<iframe src="https://www.youtube.com/embed/v6HFa4y6hgw?rel=0&modestbranding=1&autohide=1&showinfo=0&controls=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>*@
                                        <iframe src="@item.VideoUrl?rel=0&modestbranding=1&autohide=1&showinfo=0&controls=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                    </div>

                                    <div class="matter">
                                        <h2>@item.Title</h2>
                                        <div class="date"><i class="fa fa-clock-o" aria-hidden="true"></i>@item.PostDate</div>

                                    </div>


                                </a>
                            </div>
                        }
                    }
                </div>

                @*<div class="row mb-5">
                        <div class="col-12 text-center">
                            <button class="btn btn-dark btn-lg">Load More</button>
                        </div>
                    </div>*@
                @if (TotalPaginationCount > 6)
            {
                    <nav aria-label="Page navigation example" class="paging_wrap extra-margin-top-100">
                        <ul class="pagination">
                            <li class="page-item">
                                @if (PrePage > 0)
                {
                    PrePage = PrePage - 6;
                                    <a class="page-link" href="@baseUrlPath/MobileApp/video?page=@PrePage" aria-label="Previous">
                                        <span aria-hidden="true"><i class="icon-prev"></i></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                }

                            </li>

                            @{
                                int pagination = 0;
                                for (int i = 1; i <= pagenationOffSet; i++)
                                {

                                    if (page == pagination)
                                    {
                                        <li class="page-item  active"><a class="page-link" href="@baseUrlPath/MobileApp/video?page=@pagination">@i</a></li>
                                    }
                                    else
                                    {
                                        <li class="page-item"><a class="page-link" href="@baseUrlPath/MobileApp/video?page=@pagination">@i</a></li>
                                    }
                                    pagination = pagination + 6;
                                }
                            }

                            @{
                                NextPage = TotalPaginationCount - NextPage;
                                NextPage = NextPage - 6;
                                <li class="page-item">
                                    @if (NextPage > 0)
                                    {
                                        page = page + 6;
                                        <a class="page-link" href="@baseUrlPath/MobileApp/video?page=@page" aria-label="Next">
                                            <span aria-hidden="true"><i class="icon-next"></i></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    }
                                    else
                                    {

                                    }
                                </li>

                            }

                        </ul>
                    </nav>

                                }

            </div>
        @*</div>*@
    @*</div>*@

    
    <script>
      AOS.init({
        easing: 'ease-in-out-sine'
      });
    </script>

    <script>
            $(function () {
                $('#ddlCategorylist').change(function () {
                    $('#myform').submit();
                });
            });
    </script>

</body>
</html>